# Generated by Django 5.2.17 on 2026-09-23 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looked_up_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('source', models.CharField(choices=[('rest', 'REST'), ('graphql', 'GraphQL')], max_length=10)),
                ('coin_id', models.CharField(max_length=100)),
                ('base_currency', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('change_24h_percent', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('quote_currency', models.CharField(blank=True, max_length=3)),
                ('quote_price', models.DecimalField(decimal_places=10, max_digits=24, null=True)),
                ('rate_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-looked_up_at'],
                'indexes': [models.Index(fields=['coin_id', '-looked_up_at'], name='markets_pri_coin_id_583c50_idx')],
            },
        ),
    ]
